#!/bin/bash
set -euo pipefail

# WireGuard Management Layer - Client Connect Script
# Generated by the server management daemon.
# Placeholders: __SERVER_PUBLIC_IP__, __MGMT_PORT__, __API_KEY__, __DEFAULT_DNS__

SERVER_IP="__SERVER_PUBLIC_IP__"
MGMT_PORT="__MGMT_PORT__"
API_KEY="__API_KEY__"
DEFAULT_DNS="__DEFAULT_DNS__"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()    { echo -e "${GREEN}[+]${NC} $*"; }
warn()   { echo -e "${YELLOW}[!]${NC} $*"; }
error()  { echo -e "${RED}[x]${NC} $*"; }

# ──────────────────────────────────────────────────────

check_root() {
    if [[ "$(id -u)" -ne 0 ]]; then
        error "This script must be run as root (use sudo bash)"
        exit 1
    fi
}

detect_os() {
    if [[ "$(uname)" == "Darwin" ]]; then
        OS="macos"
    elif [[ -f /etc/os-release ]]; then
        . /etc/os-release
        OS="$ID"
    elif command -v apt-get &>/dev/null; then
        OS="debian"
    elif command -v dnf &>/dev/null; then
        OS="fedora"
    elif command -v yum &>/dev/null; then
        OS="centos"
    elif command -v pacman &>/dev/null; then
        OS="arch"
    else
        error "Cannot detect OS"
        exit 1
    fi
    log "Detected OS: $OS"
}

install_wireguard() {
    if command -v wg &>/dev/null; then
        log "WireGuard tools already installed ($(wg --version 2>&1 | head -1))"
        return
    fi

    log "Installing WireGuard..."

    case "$OS" in
        ubuntu|debian)
            apt-get update -qq
            apt-get install -y wireguard wireguard-tools
            ;;
        fedora|centos|rhel|rocky|alma)
            if command -v dnf &>/dev/null; then
                dnf install -y wireguard-tools
            else
                yum install -y epel-release
                yum install -y wireguard-tools
            fi
            ;;
        arch)
            pacman -Sy --noconfirm wireguard-tools
            ;;
        macos)
            if ! command -v brew &>/dev/null; then
                error "Homebrew not found. Please install Homebrew first: https://brew.sh"
                exit 1
            fi
            brew install wireguard-tools
            ;;
        *)
            error "Unsupported OS for auto-install: $OS"
            error "Please install wireguard-tools manually and re-run this script."
            exit 1
            ;;
    esac

    log "WireGuard installed"
}

get_hostname() {
    local name
    name=$(hostname 2>/dev/null || cat /etc/hostname 2>/dev/null || echo "unknown")
    echo "$name"
}

register_with_server() {
    local hostname="$1"

    log "Registering with management server as '$hostname'..."

    local resp
    resp=$(curl -sSf -X POST "http://${SERVER_IP}:${MGMT_PORT}/api/v1/register" \
        -H "Authorization: Bearer ${API_KEY}" \
        -H "Content-Type: application/json" \
        -d "{\"hostname\":\"${hostname}\",\"dns\":\"${DEFAULT_DNS}\"}" 2>&1) || {
        error "Failed to connect to management server"
        error "Response: $resp"
        exit 1
    }

    if echo "$resp" | grep -q '"error"'; then
        local err_msg
        err_msg=$(echo "$resp" | grep -o '"error":"[^"]*"' | head -1 | cut -d'"' -f4)
        error "Registration failed: $err_msg"
        echo "$resp" | python3 -m json.tool 2>/dev/null || echo "$resp"
        exit 1
    fi

    PEER_NAME=$(echo "$resp" | python3 -c "import sys,json; print(json.load(sys.stdin)['peer']['name'])" 2>/dev/null || echo "$hostname")
    PEER_ADDRESS=$(echo "$resp" | python3 -c "import sys,json; print(json.load(sys.stdin)['peer']['address'])" 2>/dev/null || echo "")
    PEER_PRIVATE_KEY=$(echo "$resp" | python3 -c "import sys,json; print(json.load(sys.stdin)['peer']['private_key'])" 2>/dev/null || echo "")
    SERVER_PUBLIC_KEY=$(echo "$resp" | python3 -c "import sys,json; print(json.load(sys.stdin)['peer']['server_public_key'])" 2>/dev/null || echo "")
    SERVER_ENDPOINT=$(echo "$resp" | python3 -c "import sys,json; print(json.load(sys.stdin)['peer']['server_endpoint'])" 2>/dev/null || echo "")
    PEER_DNS=$(echo "$resp" | python3 -c "import sys,json; print(json.load(sys.stdin)['peer']['dns'])" 2>/dev/null || echo "$DEFAULT_DNS")
    PEER_KEEPALIVE=$(echo "$resp" | python3 -c "import sys,json; print(json.load(sys.stdin)['peer']['keepalive'])" 2>/dev/null || echo "25")

    log "Registered successfully as $PEER_NAME ($PEER_ADDRESS)"
}

write_config() {
    local wg_conf="/etc/wireguard/${WG_INTERFACE:-wg0}.conf"
    local wg_interface="${WG_INTERFACE:-wg0}"

    if [[ ! -d /etc/wireguard ]]; then
        mkdir -p /etc/wireguard
    fi

    log "Writing WireGuard config to $wg_conf..."

    cat > "$wg_conf" << WGCONF
[Interface]
Address = $PEER_ADDRESS
PrivateKey = $PEER_PRIVATE_KEY
DNS = $PEER_DNS

[Peer]
PublicKey = $SERVER_PUBLIC_KEY
Endpoint = $SERVER_ENDPOINT
AllowedIPs = $WG_ALLOWED_IPS
PersistentKeepalive = $PEER_KEEPALIVE
WGCONF

    WG_INTERFACE="$wg_interface"

    chmod 600 "$wg_conf"
}

start_wireguard() {
    log "Starting WireGuard..."

    case "$OS" in
        ubuntu|debian|fedora|centos|rhel|rocky|alma|arch)
            if command -v systemctl &>/dev/null; then
                systemctl enable "wg-quick@${WG_INTERFACE}" --quiet
                systemctl restart "wg-quick@${WG_INTERFACE}"
            elif command -v service &>/dev/null; then
                service "wg-quick@${WG_INTERFACE}" restart
            else
                wg-quick up "${WG_INTERFACE}" || true
            fi
            ;;
        macos)
            wg-quick up "${WG_INTERFACE}" &
            ;;
        *)
            wg-quick up "${WG_INTERFACE}" &
            ;;
    esac
}

verify_connection() {
    sleep 1
    local gateway_ip="${SERVER_ENDPOINT%:*}"

    log "Verifying connection..."

    if ping -c 2 -W 3 "${PEER_ADDRESS%/*}" &>/dev/null; then
        warn "Self-ping ok (interface is up)"
    fi

    if ping -c 2 -W 3 "$gateway_ip" &>/dev/null 2>&1 || true; then
        log "WireGuard tunnel established"
    fi

    log "Checking WireGuard status..."
    wg show "${WG_INTERFACE}" 2>/dev/null || true
}

# ──────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────

echo ""
echo -e "${CYAN}╔════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   WireGuard Management Layer - Client      ║${NC}"
echo -e "${CYAN}║   Auto-Connection Script                   ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════╝${NC}"
echo ""

check_root
detect_os
install_wireguard

WG_INTERFACE="wg0"
WG_ALLOWED_IPS="__WG_ALLOWED_IPS__"

HOSTNAME=$(get_hostname)
register_with_server "$HOSTNAME"
write_config
start_wireguard
verify_connection

echo ""
echo -e "${GREEN}${BOLD}Successfully connected to VPN!${NC}"
echo -e "  Your VPN IP: ${CYAN}${PEER_ADDRESS}${NC}"
echo -e "  Gateway:     ${CYAN}${SERVER_IP}${NC}"
echo ""
